@url = http://localhost:1234/api
# @url = http://myaliyun:8080/api

@json = Content-Type: application/json

### 
GET {{url}}

###
GET {{url}}/test

### 注册
POST {{url}}/register
{{json}}

{
    "username": "wdwada",
    "password": "12345678"
}

### 登录
POST {{url}}/login
{{json}}

{
    "username": "minu",
    "password": "123456"
}

### 用户列表
GET {{url}}/users 


### 个人信息
GET {{url}}/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTg4YjU0MmM3ZDc4MmQ0OGZhYjU1ZCIsImlhdCI6MTYwOTA3NTU2OX0.yYY5iXHB0tvb2vUEN4RkDDM7WsLXXUNCZkk4dZAuT8I

### 添加视频
POST {{url}}/video/create
{{json}}

{
    "videoId": "bv003",
    "title": "哈哈哈哈哈3"
}

### 视频列表
GET {{url}}/videos
{{json}}

### 收藏视频, 应该发送token
### 首先是登陆状态，服务器获取到请求头的token，前台传入videoId
POST {{url}}/collect
{{json}}
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmZTg4YjU0MmM3ZDc4MmQ0OGZhYjU1ZCIsImlhdCI6MTYwOTA3NTU2OX0.yYY5iXHB0tvb2vUEN4RkDDM7WsLXXUNCZkk4dZAuT8I

{
    "videoId": "bv002"
}




